"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load .env file
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ha%=6u*hb!+orxa^g6e_uh83#!xuyx7f$nka2m&z-ab+kcy9!!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',  # ASGI server 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'cloudinary_storage',
    'cloudinary',
    'channels',
    'django_eventstream',
    
    # ===== Core Domain =====
    'apps.core.users',
    
    # ===== Geography Domain =====
    'apps.geography.provinces',
    'apps.geography.communes',
    'apps.geography.addresses',
    
    # ===== Company Domain =====
    'apps.company.companies',
    'apps.company.industries',
    'apps.company.benefit_categories',
    'apps.company.company_benefits',
    'apps.company.media_types',
    'apps.company.company_media',
    
    # ===== Recruitment Domain =====
    'apps.recruitment.jobs',
    'apps.recruitment.job_categories',
    'apps.recruitment.campaigns',
    'apps.recruitment.referrals',
    
    # Billing Module
    'apps.billing',
    'apps.recruitment.job_skills',
    'apps.recruitment.job_locations',
    'apps.recruitment.applications',
    'apps.recruitment.application_status_history',
    'apps.recruitment.interviews',
    'apps.recruitment.interview_types',
    'apps.recruitment.interview_interviewers',
    'apps.recruitment.saved_jobs',
    'apps.recruitment.job_views',
    # 'apps.recruitment.recruitment_campaigns',
    # 'apps.recruitment.campaign_jobs', 
    
    # ===== Candidate Domain =====
    'apps.candidate.recruiters',
    'apps.candidate.recruiter_education',
    'apps.candidate.recruiter_experience',
    'apps.candidate.recruiter_skills',
    'apps.candidate.recruiter_certifications',
    'apps.candidate.recruiter_languages',
    'apps.candidate.recruiter_projects',
    'apps.candidate.recruiter_cvs',
    'apps.candidate.cv_templates',
    'apps.candidate.cv_template_categories',
    'apps.candidate.skills',
    'apps.candidate.skill_categories',
    'apps.candidate.languages',
    
    # ===== Assessment Domain =====
    'apps.assessment.assessment_tests',
    'apps.assessment.assessment_categories',
    'apps.assessment.job_assessment_requirements',
    'apps.assessment.test_results',
    'apps.assessment.ai_matching_scores',
    
    # ===== Social Domain =====
    'apps.social.reviews',
    'apps.social.review_reactions',
    'apps.social.recommendations',
    'apps.social.recruiter_connections',
    'apps.social.skill_endorsements',
    'apps.social.company_followers',
    'apps.social.referral_programs',
    'apps.social.referrals',
    
    # ===== Communication Domain =====
    'apps.communication.notifications',
    'apps.communication.notification_types',
    'apps.communication.messages',
    'apps.communication.message_threads',
    'apps.communication.message_participants',
    'apps.communication.job_alerts',
    'apps.communication.job_alert_skills',
    
    # ===== Billing Domain =====
    # 'apps.billing.subscription_plans',
    # 'apps.billing.company_subscriptions', 
    # 'apps.billing.payment_methods',
    # 'apps.billing.payment_transactions',
    
    # ===== Email Domain =====
    'apps.email',
    # 'apps.email.email_templates',
    # 'apps.email.email_template_categories', 
    # 'apps.email.email_campaigns',
    # 'apps.email.email_logs',
    # 'apps.email.sent_emails',
    
    # ===== Blog Domain =====
    'apps.blog',
    # 'apps.blog.blog_posts',
    # 'apps.blog.blog_categories',
    # 'apps.blog.blog_tags',
    # 'apps.blog.blog_post_tags',
    # 'apps.blog.blog_comments',
    
    # ===== System Domain =====
    'apps.system.system_settings',
    'apps.system.activity_logs',
    'apps.system.activity_log_types',
    'apps.system.file_uploads',
    
    # ===== Analytics Domain =====
    'apps.analytics',
    # 'apps.system.analytics_reports',
    # 'apps.system.analytics_daily_statistics',
    # 'apps.system.report_types',
    # 'apps.system.reports',
    'apps.system.audit_logs',
    'apps.system.search_history',
    'apps.system.faqs',
    'apps.system.job_search_history',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Channel Layers với Redis cho real-time
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.getenv("REDIS_HOST", "localhost"), 6379)],
        },
    },
}

# EventStream Settings cho SSE
EVENTSTREAM_STORAGE_CLASS = 'django_eventstream.storage.DjangoModelStorage'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'jobportal_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'postgres'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Cloudinary Storage
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

if os.getenv('CLOUDINARY_CLOUD_NAME'):
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    MEDIA_URL = '/media/'  # Cloudinary handles the actual URL generation
else:
    DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'
    MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core_users.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4000",
]

CORS_ALLOW_CREDENTIALS = True

# ===== Email Configuration =====
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
