# Generated by Django 5.2.10 on 2026-01-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_message_threads', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='last_message_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Thời gian tin nhắn cuối'),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='last_message_content',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung tin nhắn cuối'),
        ),
    ]
