# Generated by Django 5.2.10 on 2026-01-24 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_recruiter_education', '0002_initial'),
        ('candidate_recruiters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitereducation',
            options={'ordering': ['-start_date', 'display_order'], 'verbose_name': 'Recruiter education', 'verbose_name_plural': 'Recruiter education'},
        ),
        migrations.AlterField(
            model_name='recruitereducation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='recruitereducation',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='recruitereducation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='recruitereducation',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='recruitereducation',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='recruitereducation',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Field of study'),
        ),
        migrations.AlterField(
            model_name='recruitereducation',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Is current'),
        ),
        migrations.AlterField(
            model_name='recruitereducation',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='candidate_recruiters.recruiter', verbose_name='Recruiter'),
        ),
        migrations.AlterField(
            model_name='recruitereducation',
            name='school_name',
            field=models.CharField(max_length=255, verbose_name='School name'),
        ),
        migrations.AlterField(
            model_name='recruitereducation',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='recruitereducation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
