# Generated by Django 5.2.10 on 2026-01-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication_messages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
