# Generated by Django 5.2.10 on 2026-01-20 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_skills', '0001_initial'),
        ('communication_job_alerts', '0001_initial'),
        ('geography_provinces', '0001_initial'),
        ('recruitment_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobalert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Thông báo việc làm', 'verbose_name_plural': 'Thông báo việc làm'},
        ),
        migrations.RemoveField(
            model_name='jobalert',
            name='province',
        ),
        migrations.RemoveField(
            model_name='jobalert',
            name='salary_max',
        ),
        migrations.AddField(
            model_name='jobalert',
            name='email_notification',
            field=models.BooleanField(default=True, verbose_name='Nhận email thông báo'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='job_alerts', to='geography_provinces.province', verbose_name='Địa điểm làm việc'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='job_alerts', to='candidate_skills.skill', verbose_name='Kỹ năng'),
        ),
        migrations.CreateModel(
            name='JobAlertMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Đã gửi thông báo')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Đã xem')),
                ('matched_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Thời điểm khớp')),
                ('score', models.FloatField(default=0.0, verbose_name='Điểm phù hợp')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_matches', to='recruitment_jobs.job', verbose_name='Việc làm')),
                ('job_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='communication_job_alerts.jobalert', verbose_name='Job Alert')),
            ],
            options={
                'verbose_name': 'Kết quả khớp job',
                'verbose_name_plural': 'Kết quả khớp job',
                'db_table': 'job_alert_matches',
                'ordering': ['-matched_at'],
                'unique_together': {('job_alert', 'job')},
            },
        ),
    ]
