# Generated by Django 5.2.10 on 2026-01-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication_job_alerts', '0002_alter_jobalert_options_remove_jobalert_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobalert',
            name='use_ai_matching',
            field=models.BooleanField(default=True, verbose_name='Sử dụng AI Match'),
        ),
    ]
