# Generated by Django 6.0.1 on 2026-01-17 02:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại')),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL ảnh đại diện')),
                ('role', models.CharField(choices=[('recruiter', 'Ứng viên'), ('company', 'Công ty'), ('admin', 'Quản trị viên')], db_index=True, default='recruiter', max_length=20, verbose_name='Vai trò')),
                ('status', models.CharField(choices=[('active', 'Hoạt động'), ('inactive', 'Không hoạt động'), ('banned', 'Bị khóa')], db_index=True, default='active', max_length=20, verbose_name='Trạng thái')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email đã xác minh')),
                ('email_verification_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token xác minh email')),
                ('password_reset_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token reset mật khẩu')),
                ('password_reset_expires', models.DateTimeField(blank=True, null=True, verbose_name='Hạn reset mật khẩu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'db_table': 'users',
            },
        ),
    ]
