# Generated by Django 6.0.1 on 2026-01-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='Kích hoạt 2FA'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã bí mật 2FA'),
        ),
    ]
