# Generated by Django 5.2.10 on 2026-01-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_companysubscription_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vnp_BankCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vnp_CardType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vnp_OrderInfo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vnp_TransactionNo',
            field=models.CharField(blank=True, help_text='Transaction ID at VNPay System', max_length=100, null=True),
        ),
    ]
