# Generated by Django 5.2.10 on 2026-01-21 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_companies', '0002_allow_null_user'),
        ('recruitment_jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='VND', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='draft', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_referral_programs', to='company_companies.company')),
                ('jobs', models.ManyToManyField(blank=True, related_name='referral_programs', to='recruitment_jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_phone', models.CharField(max_length=20)),
                ('cv_file', models.URLField(blank=True, help_text='Cloudinary URL of CV file', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('interviewing', 'Interviewing'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('referral_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_referrals', to='recruitment_jobs.job')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_referrals_made', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='recruitment_referrals.referralprogram')),
            ],
            options={
                'ordering': ['-referral_date'],
            },
        ),
    ]
