# Generated by Django 5.2.10 on 2026-01-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_referrals', '0001_cloudinary_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày thanh toán'),
        ),
        migrations.AddField(
            model_name='referralprogram',
            name='reward_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Salary')], default='fixed', max_length=20, verbose_name='Loại thưởng'),
        ),
        migrations.AlterField(
            model_name='referralprogram',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Giá trị thưởng (Tiền hoặc %)'),
        ),
    ]
