# Generated by Django 5.2.10 on 2026-01-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_assessment_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttest',
            name='max_retakes',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lần thi lại tối đa'),
        ),
        migrations.AddField(
            model_name='assessmenttest',
            name='retake_wait_days',
            field=models.PositiveIntegerField(default=7, verbose_name='Thời gian chờ thi lại (ngày)'),
        ),
    ]
